# Generated by Django 6.0.2 on 2026-03-27 10:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklylog',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='log_attachments/'),
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='challenges',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='hours',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='supervisor_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='weeklylog',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='weeklylog',
            unique_together={('student', 'week')},
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='placements', to=settings.AUTH_USER_MODEL)),
                ('workplace_supervisor', models.ForeignKey(blank=True, limit_choices_to={'role': 'WORKPLACE_SUPERVISOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_placements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinalGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('grade_letter', models.CharField(blank=True, max_length=5)),
                ('published', models.BooleanField(default=False)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('computed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='computed_grades', to=settings.AUTH_USER_MODEL)),
                ('placement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_grade', to='internship.placement')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_skills', models.IntegerField(default=0)),
                ('communication_skills', models.IntegerField(default=0)),
                ('punctuality', models.IntegerField(default=0)),
                ('overall_comments', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Reviewed', 'Reviewed')], default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_evaluations', to=settings.AUTH_USER_MODEL)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='internship.placement')),
            ],
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='placement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='internship.placement'),
        ),
    ]
