# Generated by Django 6.0.2 on 2026-03-27 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0002_weeklylog_attachment_weeklylog_challenges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='academic_supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'ACADEMIC_SUPERVISOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_supervised_placements', to=settings.AUTH_USER_MODEL),
        ),
    ]
