# Generated by Django 6.0.2 on 2026-04-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0003_placement_academic_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
