# Generated by Django 6.0.2 on 2026-04-23 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0005_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeklylog',
            old_name='tasks',
            new_name='description',
        ),
    ]
